

name: CI-CD
# Controla quando será executado o workflow
on:

  # Definimos o que vai disparar o workflow 
  push:
    branches: [ main ]

  # Permite executar o workflow manualmente
  workflow_dispatch:

# Definimos os jobs que serão executados
jobs:
  # TJob de Build
  build:
    # Onde sera rodado o Job
    runs-on: ubuntu-latest

    # Tasks do job
    steps:
      # EXEMPLO DE ACTION
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # EXEMPLO DE COMANDO
      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
      
      - name: Docker Login

        uses: docker/login-action@v1.12.0
        with:
          # Usando secrets do github
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


